HW-III-3.2-lesson_3.4-done
slavzick/HW-III-3.2 pull request #1
Opened 2022-11-03 18:35 UTC by slavzick

2022-11-04 08:14 UTC, OlgaLugacheva requested changes

2022-11-04 08:14 UTC, OlgaLugacheva commented on src/main/java/pro/sky/hwiii32/scripts.sql
> +select * from student where id>student.age;
должно работать просто id> age

2022-11-04 09:23 UTC, slavzick commented on src/main/java/pro/sky/hwiii32/record/FacultyRecord.java
> +public class FacultyRecord {
Я бы написал и Dto, в этом плане я чистый лист. а принято везде не одинаково

2022-11-04 09:24 UTC, slavzick commented on src/main/java/pro/sky/hwiii32/component/RecordMapper.java
> +//    private int age;
Спасибо. Буду изучать

2022-11-04 09:27 UTC, slavzick commented on src/main/java/pro/sky/hwiii32/repository/StudentRepository.java
> +    List<Student> findStudentsByFaculty_Id(Long facultyId);
Исправлю

2022-11-04 09:28 UTC, slavzick commented on src/main/java/pro/sky/hwiii32/scripts.sql
> +select * from student where id>student.age;
понял

2022-11-12 08:55 UTC, BizinMitya commented on src/main/java/pro/sky/hwiii32/scripts423.sql
> +         inner join faculty on faculty.id = student.faculty_id;
здесь предполагался left join, т.к. нужны все студенты, а не только те, у которых проставлен факультет)

2022-11-12 08:56 UTC, BizinMitya commented on src/main/java/pro/sky/hwiii32/scripts423.sql
> +select student.* from student right join avatar a on student.id = a.student_id
а здесь inner join, т.к. нужны только те, у которых есть аватар

2022-11-14 07:42 UTC, slavzick commented on src/main/java/pro/sky/hwiii32/scripts423.sql
> +         inner join faculty on faculty.id = student.faculty_id;
Понял. спасибо

2022-11-14 07:42 UTC, slavzick commented on src/main/java/pro/sky/hwiii32/scripts423.sql
> +select student.* from student right join avatar a on student.id = a.student_id
Тоже понял. поправлю. спасибо

2022-11-17 06:51 UTC, volalex commented on src/main/java/pro/sky/hwiii32/service/FacultyService.java
> +    final Logger logger = LoggerFactory.getLogger(FacultyService.class);
Любые логгеры лучше объявлять как private final static, нам нет смысла создавать логгер на каждый объект

2022-11-17 11:40 UTC, slavzick commented on src/main/java/pro/sky/hwiii32/service/FacultyService.java
> +    final Logger logger = LoggerFactory.getLogger(FacultyService.class);
Исправлю, спасибо

2022-11-18 06:43 UTC, merged